AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create a Lambda Layer from an S3-hosted ZIP file.

Parameters:
  S3DeploymentBucket:
    Type: String
    Description: Name of the S3 bucket containing the layer ZIP file

  LayerS3Key:
    Type: String
    Description: S3 key (path) to the layer ZIP file (e.g., 'layers/core_layer.zip')

  LayerName:
    Type: String
    Default: core-layer
    Description: Name of the Lambda Layer

Resources:
  CoreLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Ref LayerName
      Description: Shared core module
      Content:
        S3Bucket: !Ref S3DeploymentBucket
        S3Key: !Ref LayerS3Key
      CompatibleRuntimes:
        - python3.12

Outputs:
  CoreLayerArn:
    Description: ARN of the Lambda Layer
    Value: !Ref CoreLayer
