AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create a Lambda Layer from an S3-hosted ZIP file.

Parameters:
  S3DeploymentBucket:
    Type: String
    Description: Name of the S3 bucket containing the layer ZIP file

  LayerS3Key:
    Type: String
    Description: S3 key (path) to the layer ZIP file (e.g., 'azrius/20250424/requirements.zip')

  LayerName:
    Type: String
    Default: requirements-layer
    Description: Name of the Lambda Layer

Resources:
  RequirementsLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Ref LayerName
      Description: Requirements Python dependencies
      Content:
        S3Bucket: !Ref S3DeploymentBucket
        S3Key: !Ref LayerS3Key
      CompatibleRuntimes:
        - python3.12

Outputs:
  RequirementsLayerArn:
    Description: ARN of the Requirements Lambda Layer
    Value: !Ref RequirementsLayer
